
    create table person (
       id bigint generated by default as identity,
        birth_date date,
        cpf varchar(255) not null,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        primary key (id)
    );

    create table person_phones (
       person_id bigint not null,
        phones_id bigint not null
    );

    create table phone (
       id bigint generated by default as identity,
        number varchar(255) not null,
        type varchar(255) not null,
        primary key (id)
    );

    alter table person 
       add constraint UK_ovihp2p82c97wbe60mv11txrj unique (cpf);

    alter table person_phones 
       add constraint UK_haq8fex9okoi3kpaxmqe1kpcl unique (phones_id);

    alter table person_phones 
       add constraint FKincp66whfw4olpi3osmd8mylw 
       foreign key (phones_id) 
       references phone;

    alter table person_phones 
       add constraint FKo03nn6lgnt28li9oxmhu65esh 
       foreign key (person_id) 
       references person;
